# Generated by Django 5.0.6 on 2024-05-19 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('description', models.TextField(blank=True, null=True)),
                ('contacts', models.CharField(blank=True, max_length=40, null=True)),
                ('youtube_url', models.CharField(blank=True, help_text='Link to owners youtube', max_length=100, null=True)),
                ('linkedin_url', models.CharField(blank=True, help_text='Link to owners linked in', max_length=100, null=True)),
                ('github_url', models.CharField(blank=True, help_text='Link to owners github', max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
