# Generated by Django 5.0.6 on 2024-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='courseitemmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
